using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Frame.ServiceLayer.Modelos.Pedido
{
    public class CadastrosPedidos
    {
        public CadastroPedido[] value { get; set; }
    }
    public class CadastroPedido
    {
        //public CadastroJob[] CadastroJob { get; set; }

        public string odatametadata { get; set; }
        public int? DocEntry { get; set; }
        public int? DocNum { get; set; }
        public string DocType { get; set; }
        public string HandWritten { get; set; }
        public string Printed { get; set; }
        public string DocDate { get; set; }
        public string DocDueDate { get; set; }
        public string CardCode { get; set; }

        public string Posted { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public object NumAtCard { get; set; }
        public float? DocTotal { get; set; }
        public int? AttachmentEntry { get; set; }
        public string DocCurrency { get; set; }
        public float? DocRate { get; set; }
        public string Reference1 { get; set; }
        public object Reference2 { get; set; }
        public object Comments { get; set; }
        public string JournalMemo { get; set; }
        public int? PaymentGroupCode { get; set; }
        public string DocTime { get; set; }
        public string SalesPersonCode { get; set; }
        public int? TransportationCode { get; set; }
        public string Confirmed { get; set; }
        public object ImportFileNum { get; set; }
        public string SummeryType { get; set; }
        public int? ContactPersonCode { get; set; }
        public string ShowSCN { get; set; }
        public int? Series { get; set; }
        public string TaxDate { get; set; }
        public string PartialSupply { get; set; }
        public string DocObjectCode { get; set; }
        public string ShipToCode { get; set; }
        public object Indicator { get; set; }
        public object FederalTaxID { get; set; }
        public float? DiscountPercent { get; set; }
        public object PaymentReference { get; set; }
        public string CreationDate { get; set; }
        public string UpdateDate { get; set; }
        public int? FinancialPeriod { get; set; }
        public object TransNum { get; set; }
        public float? VatSum { get; set; }
        public float? VatSumSys { get; set; }
        public float? VatSumFc { get; set; }
        public string NetProcedure { get; set; }
        public float? DocTotalFc { get; set; }
        public float? DocTotalSys { get; set; }
        public object Form1099 { get; set; }
        public object Box1099 { get; set; }
        public string RevisionPo { get; set; }
        public string RequriedDate { get; set; }
        public string CancelDate { get; set; }
        public string BlockDunning { get; set; }
        public string Submitted { get; set; }
        public int? Segment { get; set; }
        public string PickStatus { get; set; }
        public string Pick { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentBlock { get; set; }
        public object PaymentBlockEntry { get; set; }
        public object CentralBankIndicator { get; set; }
        public string MaximumCashDiscount { get; set; }
        public string Reserve { get; set; }
        public object Project { get; set; }
        public object ExemptionValidityDateFrom { get; set; }
        public object ExemptionValidityDateTo { get; set; }
        public string WareHouseUpdateType { get; set; }
        public string Rounding { get; set; }
        public object ExternalCorrectedDocNum { get; set; }
        public object InternalCorrectedDocNum { get; set; }
        public object NextCorrectingDocument { get; set; }
        public string DeferredTax { get; set; }
        public object TaxExemptionLetterNum { get; set; }
        public float? WTApplied { get; set; }
        public float? WTAppliedFC { get; set; }
        public string BillOfExchangeReserved { get; set; }
        public object AgentCode { get; set; }
        public float? WTAppliedSC { get; set; }
        public float? TotalEqualizationTax { get; set; }
        public float? TotalEqualizationTaxFC { get; set; }
        public float? TotalEqualizationTaxSC { get; set; }
        public int? NumberOfInstallments { get; set; }
        public string ApplyTaxOnFirstInstallment { get; set; }
        public float? WTNonSubjectAmount { get; set; }
        public float? WTNonSubjectAmountSC { get; set; }
        public float? WTNonSubjectAmountFC { get; set; }
        public float? WTExemptedAmount { get; set; }
        public float? WTExemptedAmountSC { get; set; }
        public float? WTExemptedAmountFC { get; set; }
        public float? BaseAmount { get; set; }
        public float? BaseAmountSC { get; set; }
        public float? BaseAmountFC { get; set; }
        public float? WTAmount { get; set; }
        public float? WTAmountSC { get; set; }
        public float? WTAmountFC { get; set; }
        public object VatDate { get; set; }
        public int? DocumentsOwner { get; set; }
        public object FolioPrefixString { get; set; }
        public object FolioNumber { get; set; }
        public string DocumentSubType { get; set; }
        public object BPChannelCode { get; set; }
        public object BPChannelContact { get; set; }
        public string Address2 { get; set; }
        public string DocumentStatus { get; set; }
        public string PeriodIndicator { get; set; }
        public string PayToCode { get; set; }
        public object ManualNumber { get; set; }
        public string UseShpdGoodsAct { get; set; }
        public string IsPayToBank { get; set; }
        public object PayToBankCountry { get; set; }
        public object PayToBankCode { get; set; }
        public object PayToBankAccountNo { get; set; }
        public object PayToBankBranch { get; set; }
        public int? BPL_IDAssignedToInvoice { get; set; }
        public float? DownPayment { get; set; }
        public string ReserveInvoice { get; set; }
        public int? LanguageCode { get; set; }
        public object TrackingNumber { get; set; }
        public object PickRemark { get; set; }
        public object ClosingDate { get; set; }
        public object SequenceCode { get; set; }
        public object SequenceSerial { get; set; }
        public object SeriesString { get; set; }
        public object SubSeriesString { get; set; }
        public string SequenceModel { get; set; }
        public string UseCorrectionVATGroup { get; set; }
        public float? TotalDiscount { get; set; }
        public float? DownPaymentAmount { get; set; }
        public float? DownPaymentPercentage { get; set; }
        public string DownPaymentType { get; set; }
        public float? DownPaymentAmountSC { get; set; }
        public float? DownPaymentAmountFC { get; set; }
        public float? VatPercent { get; set; }
        public float? ServiceGrossProfitPercent { get; set; }
        public object OpeningRemarks { get; set; }
        public object ClosingRemarks { get; set; }
        public float? RoundingDiffAmount { get; set; }
        public float? RoundingDiffAmountFC { get; set; }
        public float? RoundingDiffAmountSC { get; set; }
        public string Cancelled { get; set; }
        public object SignatureInputMessage { get; set; }
        public object SignatureDigest { get; set; }
        public object CertificationNumber { get; set; }
        public object PrivateKeyVersion { get; set; }
        public string ControlAccount { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string ArchiveNonremovableSalesQuotation { get; set; }
        public object GTSChecker { get; set; }
        public object GTSPayee { get; set; }
        public int? ExtraMonth { get; set; }
        public int? ExtraDays { get; set; }
        public int? CashDiscountDateOffset { get; set; }
        public string StartFrom { get; set; }
        public string NTSApproved { get; set; }
        public object ETaxWebSite { get; set; }
        public object ETaxNumber { get; set; }
        public object NTSApprovedNumber { get; set; }
        public string EDocGenerationType { get; set; }
        public object EDocSeries { get; set; }
        public object EDocNum { get; set; }
        public object EDocExportFormat { get; set; }
        public string EDocStatus { get; set; }
        public object EDocErrorCode { get; set; }
        public object EDocErrorMessage { get; set; }
        public string DownPaymentStatus { get; set; }
        public object GroupSeries { get; set; }
        public object GroupNumber { get; set; }
        public string GroupHandWritten { get; set; }
        public object ReopenOriginalDocument { get; set; }
        public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        public string CreateOnlineQuotation { get; set; }
        public object POSEquipmentNumber { get; set; }
        public object POSManufacturerSerialNumber { get; set; }
        public object POSCashierNumber { get; set; }
        public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        public string ClosingOption { get; set; }
        public object SpecifiedClosingDate { get; set; }
        public string OpenForLandedCosts { get; set; }
        public string AuthorizationStatus { get; set; }
        public float? TotalDiscountFC { get; set; }
        public float? TotalDiscountSC { get; set; }
        public string RelevantToGTS { get; set; }
        public string BPLName { get; set; }
        public string VATRegNum { get; set; }
        public object AnnualInvoiceDeclarationReference { get; set; }
        public object Supplier { get; set; }
        public object Releaser { get; set; }
        public object Receiver { get; set; }
        public object BlanketAgreementNumber { get; set; }
        public string IsAlteration { get; set; }
        public string CancelStatus { get; set; }
        public object AssetValueDate { get; set; }
        public string DocumentDelivery { get; set; }
        public object AuthorizationCode { get; set; }
        public object StartDeliveryDate { get; set; }
        public object StartDeliveryTime { get; set; }
        public object EndDeliveryDate { get; set; }
        public object EndDeliveryTime { get; set; }
        public object VehiclePlate { get; set; }
        public object ATDocumentType { get; set; }
        public object ElecCommStatus { get; set; }
        public object ElecCommMessage { get; set; }
        public string ReuseDocumentNum { get; set; }
        public string ReuseNotaFiscalNum { get; set; }
        public string PrintSEPADirect { get; set; }
        public object FiscalDocNum { get; set; }
        public object POSDailySummaryNo { get; set; }
        public object POSReceiptNo { get; set; }
        public object PointOfIssueCode { get; set; }
        public object Letter { get; set; }
        public object FolioNumberFrom { get; set; }
        public object FolioNumberTo { get; set; }
        public string InterimType { get; set; }
        public int? RelatedType { get; set; }
        public object RelatedEntry { get; set; }
        public object SAPPassport { get; set; }
        public object DocumentTaxID { get; set; }
        public object DateOfReportingControlStatementVAT { get; set; }
        public object ReportingSectionControlStatementVAT { get; set; }
        public string ExcludeFromTaxReportControlStatementVAT { get; set; }
        public object POS_CashRegister { get; set; }
        public string UpdateTime { get; set; }
        public object PriceMode { get; set; }
        public string ShipFrom { get; set; }
        public string CommissionTrade { get; set; }
        public string CommissionTradeReturn { get; set; }
        public string UseBillToAddrToDetermineTax { get; set; }
        public object Cig { get; set; }
        public object Cup { get; set; }
        public object U_B1SYS_ConnTypeCode { get; set; }
        public object U_B1SYS_TensGrpCode { get; set; }
        public object U_B1SYS_EnergConsCls { get; set; }
        public object U_B1SYS_ParticipantC { get; set; }
        public object U_B1SYS_SubscrCode { get; set; }
        public object U_B1SYS_MeterCode { get; set; }
        public object U_B1SYS_RevIndC510 { get; set; }
        public object U_B1SYS_RevIndD600 { get; set; }
        public object U_B1SYS_RevIndD510 { get; set; }
        public object U_B1SYS_FisDocStatus { get; set; }
        public object U_B1SYS_CargoTranTyp { get; set; }
        public object U_B1SYS_BpSenCNPJ { get; set; }
        public object U_B1SYS_BPSenIE { get; set; }
        public object U_B1SYS_BPSenCPF { get; set; }
        public object U_B1SYS_BPSenIBGE { get; set; }
        public object U_B1SYS_BpRecCNPJ { get; set; }
        public object U_B1SYS_BPRecIE { get; set; }
        public object U_B1SYS_BPRecCPF { get; set; }
        public object U_B1SYS_BPRecIBGE { get; set; }
        public object U_B1SYS_TaxID12 { get; set; }
        public int? U_B1SYS_ImportProc { get; set; }
        public object U_B1SYS_CNPJFromC { get; set; }
        public object U_B1SYS_StateOfTP { get; set; }

        public string U_NEO_DtSol { get; set; }
        public string U_NEO_Solic { get; set; }
        public string U_NEO_Job { get; set; }
        public string U_NEO_Ag { get; set; }
        public string U_NEO_Cliente { get; set; }
        public string U_NEO_RespCamp { get; set; }
        public string U_NEO_Contrat { get; set; }
        public string U_NEO_CnpjC { get; set; }
        public string U_NEO_EmailF { get; set; }
        public string U_NEO_DtI { get; set; }
        public string U_NEO_DtF { get; set; }
        public float? U_NEO_CP { get; set; }
        public float? U_NEO_CO { get; set; }
        public string U_NEO_Marca { get; set; }
        public string U_NEO_Seg { get; set; }
        public string U_NEO_NC { get; set; }
        public string U_NEO_Excl { get; set; }
        public string U_NEO_Log { get; set; }
        public string U_NEO_LogResp { get; set; }
        public string U_NEO_LOG1 { get; set; }
        public string U_NEO_DespEv { get; set; }
        public string U_NEO_DE1 { get; set; }
        public string U_NEO_Post { get; set; }
        public string U_NEO_PostTip { get; set; }
        public string U_NEO_PzPost { get; set; }
        public string U_NEO_RePost { get; set; }
        public string U_NEO_AVF { get; set; }
        public string U_NEO_Capt { get; set; }
        public string U_NEO_TCapt { get; set; }
        public float? U_NEO_DE { get; set; }
        public string U_NEO_Ref { get; set; }
        public string U_NEO_RefV { get; set; }
        public string U_NEO_DescP { get; set; }
        public string U_NEO_CF { get; set; }
        public string U_NEO_CFEd { get; set; }
        public string U_NEO_CFResp { get; set; }
        public string U_NEO_VeicInter { get; set; }
        public string U_NEO_VeicTv { get; set; }
        public string U_NEO_VeicOOH { get; set; }
        public string U_NEO_VeicPDV { get; set; }
        public string U_NEO_VeicPz { get; set; }
        public string U_NEO_VeicTer { get; set; }
        public string U_NEO_Obs { get; set; }

        public object[] Document_ApprovalRequests { get; set; }
        public Documentline[] DocumentLines { get; set; }
        public object[] ElectronicProtocols { get; set; }
        public object[] DocumentAdditionalExpenses { get; set; }
        public object[] WithholdingTaxDataWTXCollection { get; set; }
        public object[] WithholdingTaxDataCollection { get; set; }
        public object[] DocumentSpecialLines { get; set; }
        public Taxextension TaxExtension { get; set; }
        public Addressextension AddressExtension { get; set; }
    }

    public class Taxextension
    {
        public string TaxId0 { get; set; }
        public string TaxId1 { get; set; }
        public object TaxId2 { get; set; }
        public object TaxId3 { get; set; }
        public object TaxId4 { get; set; }
        public object TaxId5 { get; set; }
        public object TaxId6 { get; set; }
        public object TaxId7 { get; set; }
        public object TaxId8 { get; set; }
        public object TaxId9 { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public object Incoterms { get; set; }
        public object Vehicle { get; set; }
        public object VehicleState { get; set; }
        public object NFRef { get; set; }
        public object Carrier { get; set; }
        public object PackQuantity { get; set; }
        public object PackDescription { get; set; }
        public object Brand { get; set; }
        public object ShipUnitNo { get; set; }
        public float? NetWeight { get; set; }
        public float? GrossWeight { get; set; }
        public string StreetS { get; set; }
        public string BlockS { get; set; }
        public string BuildingS { get; set; }
        public string CityS { get; set; }
        public string ZipCodeS { get; set; }
        public string CountyS { get; set; }
        public string StateS { get; set; }
        public string CountryS { get; set; }
        public string StreetB { get; set; }
        public string BlockB { get; set; }
        public string BuildingB { get; set; }
        public string CityB { get; set; }
        public string ZipCodeB { get; set; }
        public string CountyB { get; set; }
        public string StateB { get; set; }
        public string CountryB { get; set; }
        public object ImportOrExport { get; set; }
        public int? MainUsage { get; set; }
        public object GlobalLocationNumberS { get; set; }
        public object GlobalLocationNumberB { get; set; }
        public string TaxId12 { get; set; }
        public object TaxId13 { get; set; }
        public object BillOfEntryNo { get; set; }
        public object BillOfEntryDate { get; set; }
        public object OriginalBillOfEntryNo { get; set; }
        public object OriginalBillOfEntryDate { get; set; }
        public string ImportOrExportType { get; set; }
        public object PortCode { get; set; }
        public int? DocEntry { get; set; }
    }

    public class Addressextension
    {
        public string ShipToStreet { get; set; }
        public string ShipToStreetNo { get; set; }
        public string ShipToBlock { get; set; }
        public string ShipToBuilding { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToZipCode { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToAddressType { get; set; }
        public string BillToStreet { get; set; }
        public string BillToStreetNo { get; set; }
        public string BillToBlock { get; set; }
        public string BillToBuilding { get; set; }
        public string BillToCity { get; set; }
        public string BillToZipCode { get; set; }
        public string BillToCounty { get; set; }
        public string BillToState { get; set; }
        public string BillToCountry { get; set; }
        public string BillToAddressType { get; set; }
        public object ShipToGlobalLocationNumber { get; set; }
        public object BillToGlobalLocationNumber { get; set; }
        public object ShipToAddress2 { get; set; }
        public object ShipToAddress3 { get; set; }
        public object BillToAddress2 { get; set; }
        public object BillToAddress3 { get; set; }
        public object PlaceOfSupply { get; set; }
        public object PurchasePlaceOfSupply { get; set; }
        public int? DocEntry { get; set; }
    }

    public class Documentline
    {
        public int? LineNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public float? Quantity { get; set; }
        public string ShipDate { get; set; }
        public float? Price { get; set; }
        public float? PriceAfterVAT { get; set; }
        public string Currency { get; set; }
        public float? Rate { get; set; }
        public float? DiscountPercent { get; set; }
        public string VendorNum { get; set; }
        public object SerialNum { get; set; }
        public string WarehouseCode { get; set; }
        public int? SalesPersonCode { get; set; }
        public float? CommisionPercent { get; set; }
        public string TreeType { get; set; }
        public string AccountCode { get; set; }
        public string UseBaseUnits { get; set; }
        public string SupplierCatNum { get; set; }
        public string CostingCode { get; set; }
        public string ProjectCode { get; set; }
        public object BarCode { get; set; }
        public string VatGroup { get; set; }
        public float? Height1 { get; set; }
        public object Hight1Unit { get; set; }
        public float? Height2 { get; set; }
        public object Height2Unit { get; set; }
        public float? Lengh1 { get; set; }
        public object Lengh1Unit { get; set; }
        public float? Lengh2 { get; set; }
        public object Lengh2Unit { get; set; }
        public float? Weight1 { get; set; }
        public object Weight1Unit { get; set; }
        public float? Weight2 { get; set; }
        public object Weight2Unit { get; set; }
        public float? Factor1 { get; set; }
        public float? Factor2 { get; set; }
        public float? Factor3 { get; set; }
        public float? Factor4 { get; set; }
        public int? BaseType { get; set; }
        public object BaseEntry { get; set; }
        public object BaseLine { get; set; }
        public float? Volume { get; set; }
        public int? VolumeUnit { get; set; }
        public float? Width1 { get; set; }
        public object Width1Unit { get; set; }
        public float? Width2 { get; set; }
        public object Width2Unit { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public string TaxLiable { get; set; }
        public string PickStatus { get; set; }
        public float? PickQuantity { get; set; }
        public object PickListIdNumber { get; set; }
        public string OriginalItem { get; set; }
        public string BackOrder { get; set; }
        public string FreeText { get; set; }
        public int? ShippingMethod { get; set; }
        public object POTargetNum { get; set; }
        public string POTargetEntry { get; set; }
        public object POTargetRowNum { get; set; }
        public string CorrectionInvoiceItem { get; set; }
        public float? CorrInvAmountToStock { get; set; }
        public float? CorrInvAmountToDiffAcct { get; set; }
        public float? AppliedTax { get; set; }
        public float? AppliedTaxFC { get; set; }
        public float? AppliedTaxSC { get; set; }
        public string WTLiable { get; set; }
        public string DeferredTax { get; set; }
        public float? EqualizationTaxPercent { get; set; }
        public float? TotalEqualizationTax { get; set; }
        public float? TotalEqualizationTaxFC { get; set; }
        public float? TotalEqualizationTaxSC { get; set; }
        public float? NetTaxAmount { get; set; }
        public float? NetTaxAmountFC { get; set; }
        public float? NetTaxAmountSC { get; set; }
        public string MeasureUnit { get; set; }
        public float? UnitsOfMeasurment { get; set; }
        public float? LineTotal { get; set; }
        public float? TaxPercentagePerRow { get; set; }
        public float? TaxTotal { get; set; }
        public string ConsumerSalesForecast { get; set; }
        public float? ExciseAmount { get; set; }
        public float? TaxPerUnit { get; set; }
        public float? TotalInclTax { get; set; }
        public object CountryOrg { get; set; }
        public string SWW { get; set; }
        public object TransactionType { get; set; }
        public string DistributeExpense { get; set; }
        public float? RowTotalFC { get; set; }
        public float? RowTotalSC { get; set; }
        public float? LastBuyInmPrice { get; set; }
        public float? LastBuyDistributeSumFc { get; set; }
        public float? LastBuyDistributeSumSc { get; set; }
        public float? LastBuyDistributeSum { get; set; }
        public float? StockDistributesumForeign { get; set; }
        public float? StockDistributesumSystem { get; set; }
        public float? StockDistributesum { get; set; }
        public float? StockInmPrice { get; set; }
        public string PickStatusEx { get; set; }
        public float? TaxBeforeDPM { get; set; }
        public float? TaxBeforeDPMFC { get; set; }
        public float? TaxBeforeDPMSC { get; set; }
        public object CFOPCode { get; set; }
        public object CSTCode { get; set; }
        public int? Usage { get; set; }
        public string TaxOnly { get; set; }
        public int? VisualOrder { get; set; }
        public float? BaseOpenQuantity { get; set; }
        public float? UnitPrice { get; set; }
        public string LineStatus { get; set; }
        public float? PackageQuantity { get; set; }
        public string Text { get; set; }
        public string LineType { get; set; }
        public object COGSCostingCode { get; set; }
        public string COGSAccountCode { get; set; }
        public string ChangeAssemlyBoMWarehouse { get; set; }
        public float? GrossBuyPrice { get; set; }
        public int? GrossBase { get; set; }
        public float? GrossProfitTotalBasePrice { get; set; }
        public object CostingCode2 { get; set; }
        public object CostingCode3 { get; set; }
        public object CostingCode4 { get; set; }
        public object CostingCode5 { get; set; }
        public object ItemDetails { get; set; }
        public object LocationCode { get; set; }
        public object ActualDeliveryDate { get; set; }
        public float? RemainingOpenQuantity { get; set; }
        public float? OpenAmount { get; set; }
        public float? OpenAmountFC { get; set; }
        public float? OpenAmountSC { get; set; }
        public object ExLineNo { get; set; }
        public object RequiredDate { get; set; }
        public float? RequiredQuantity { get; set; }
        public object COGSCostingCode2 { get; set; }
        public object COGSCostingCode3 { get; set; }
        public object COGSCostingCode4 { get; set; }
        public object COGSCostingCode5 { get; set; }
        public object CSTforIPI { get; set; }
        public object CSTforPIS { get; set; }
        public object CSTforCOFINS { get; set; }
        public string CreditOriginCode { get; set; }
        public string WithoutInventoryMovement { get; set; }
        public object AgreementNo { get; set; }
        public object AgreementRowNumber { get; set; }
        public object ActualBaseEntry { get; set; }
        public object ActualBaseLine { get; set; }
        public int? DocEntry { get; set; }
        public float? Surpluses { get; set; }
        public float? DefectAndBreakup { get; set; }
        public float? Shortages { get; set; }
        public string ConsiderQuantity { get; set; }
        public string PartialRetirement { get; set; }
        public float? RetirementQuantity { get; set; }
        public float? RetirementAPC { get; set; }
        public string ThirdParty { get; set; }
        public object ExpenseType { get; set; }
        public object ReceiptNumber { get; set; }
        public object ExpenseOperationType { get; set; }
        public object FederalTaxID { get; set; }
        public object StgSeqNum { get; set; }
        public object StgEntry { get; set; }
        public object StgDesc { get; set; }
        public int? UoMEntry { get; set; }
        public string UoMCode { get; set; }
        public float? InventoryQuantity { get; set; }
        public float? RemainingOpenInventoryQuantity { get; set; }
        public object ParentLineNum { get; set; }
        public int? Incoterms { get; set; }
        public int? TransportMode { get; set; }
        public string ItemType { get; set; }
        public string ChangeInventoryQuantityIndependently { get; set; }
        public string FreeOfChargeBP { get; set; }
        public object SACEntry { get; set; }
        public object HSNEntry { get; set; }
        public float? GrossPrice { get; set; }
        public float? GrossTotal { get; set; }
        public float? GrossTotalFC { get; set; }
        public float? GrossTotalSC { get; set; }
        public int? NCMCode { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToDescription { get; set; }
        public float? U_B1SYS_IVAST { get; set; }
        public object U_B1SYS_TaxUoM { get; set; }
        public float? U_B1SYS_QtyPerTaxUoM { get; set; }
        public string U_B1SYS_RevenueInd { get; set; }
        public string U_B1SYS_RevenueInd2 { get; set; }
        public object U_B1SYS_RevenueRec { get; set; }
        public object U_B1SYS_POSTotICMS { get; set; }
        public object U_B1SYS_PSTotISSQN { get; set; }
        public object U_B1SYS_PTotICMSST { get; set; }
        public object U_B1SYS_CodigoDePar { get; set; }
        public object U_B1SYS_IPIStmpCnt { get; set; }
        public string U_NEO_Dt_Inicio { get; set; }
        public string U_NEO_Dt_fim { get; set; }
        public int? U_NEO_Entregue { get; set; }
        public int? U_NEO_Cliques { get; set; }
        public int? U_NEO_Saldo { get; set; }
        public int? U_NEO_CTR { get; set; }
        public string U_NEO_Perc_Entr { get; set; }
        public string U_NEO_RecReceita { get; set; }

        public float? U_NEO_CustoT { get; set; }


        public object[] LineTaxJurisdictions { get; set; }
        public object[] DocumentLineAdditionalExpenses { get; set; }
        public object[] WithholdingTaxLines { get; set; }
        public object[] SerialNumbers { get; set; }
        public object[] BatchNumbers { get; set; }
        public object[] DocumentLinesBinAllocations { get; set; }

    }
}
