//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulling.ValideInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValideInfo.WsSoap")]
    public interface WsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GerarToken(int codigoEmpresa, string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarToken", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GerarTokenAsync(int codigoEmpresa, string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Localiza", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Localiza(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Localiza", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> LocalizaAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroSimplesPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CadastroSimplesPF(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroSimplesPF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroSimplesPFAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroSimplesPJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CadastroSimplesPJ(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroSimplesPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroSimplesPJAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroSintetico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CadastroSintetico(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroSintetico", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroSinteticoAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroCompletoPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CadastroCompletoPF(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroCompletoPF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroCompletoPFAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroCompletoPJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CadastroCompletoPJ(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastroCompletoPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroCompletoPJAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PessoasLigadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PessoasLigadas(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PessoasLigadas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> PessoasLigadasAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPFOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReceitaFederalPFOnline(string token, string documento, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPFOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPFOnlineAsync(string token, string documento, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPFBD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReceitaFederalPFBD(string token, string documento, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPFBD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPFBDAsync(string token, string documento, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPJOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReceitaFederalPJOnline(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPJOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPJOnlineAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPJBD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReceitaFederalPJBD(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalPJBD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPJBDAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaSintegraOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReceitaSintegraOnline(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaSintegraOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaSintegraOnlineAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SintegraOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SintegraOnline(string token, string documento, string uf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SintegraOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SintegraOnlineAsync(string token, string documento, string uf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidacaoFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ValidacaoFiscal(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidacaoFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ValidacaoFiscalAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Veiculo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Veiculo(string token, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Veiculo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> VeiculoAsync(string token, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VeiculoSimples", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VeiculoSimples(string token, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VeiculoSimples", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> VeiculoSimplesAsync(string token, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObitoSimples", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObitoSimples(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObitoSimples", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObitoSimplesAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupPJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GroupPJ(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GroupPJAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimplesNacional", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SimplesNacional(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimplesNacional", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SimplesNacionalAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Protesto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Protesto(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Protesto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ProtestoAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QSA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode QSA(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QSA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> QSAAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaCEP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode BuscaCEP(string token, string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaCEP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> BuscaCEPAsync(string token, string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaCepPorLogradouro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode BuscaCepPorLogradouro(string token, string estado, string cidade, string logradouro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaCepPorLogradouro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> BuscaCepPorLogradouroAsync(string token, string estado, string cidade, string logradouro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestricaoS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RestricaoS(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestricaoS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RestricaoSAsync(string token, string documento);
        
        // CODEGEN: Parameter 'dataInicio' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Relatorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Pulling.ValideInfo.RelatorioResponse Relatorio(Pulling.ValideInfo.RelatorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Relatorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Pulling.ValideInfo.RelatorioResponse> RelatorioAsync(Pulling.ValideInfo.RelatorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ANP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ANP(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ANP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ANPAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaFGTSEmpregador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsultaFGTSEmpregador(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaFGTSEmpregador", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultaFGTSEmpregadorAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Score", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Score(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Score", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ScoreAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode IRPF(string token, string documento, int exercicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRPF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IRPFAsync(string token, string documento, int exercicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CARF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CARF(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CARF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CARFAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaTSE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsultaTSE(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaTSE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultaTSEAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CCF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CCF(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CCF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CCFAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalComCaptcha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReceitaFederalComCaptcha(string token, string cpf, string dataNascimento, string captcha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceitaFederalComCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalComCaptchaAsync(string token, string cpf, string dataNascimento, string captcha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MandadoPrisao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode MandadoPrisao(string token, string nome, string dataNascimento, string nomeMae);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MandadoPrisao", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> MandadoPrisaoAsync(string token, string nome, string dataNascimento, string nomeMae);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PEP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PEP(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PEP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> PEPAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcoesJudiciais", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AcoesJudiciais(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcoesJudiciais", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AcoesJudiciaisAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SugereGEO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SugereGEO(string token, string documento, string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SugereGEO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SugereGEOAsync(string token, string documento, string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JusBrasilPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode JusBrasilPF(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JusBrasilPF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> JusBrasilPFAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BACEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode BACEN(string token, string cnpj, string unidade, string dependencia, string operador, string mes, string ano, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BACEN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> BACENAsync(string token, string cnpj, string unidade, string dependencia, string operador, string mes, string ano, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEPIM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CEPIM(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEPIM", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CEPIMAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CEIS(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEIS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CEISAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CNEP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CNEP(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CNEP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CNEPAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PETI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PETI(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PETI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> PETIAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcordoLeniencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AcordoLeniencia(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcordoLeniencia", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AcordoLenienciaAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEAF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CEAF(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEAF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CEAFAsync(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DividaAtivaSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DividaAtivaSP(string token, string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DividaAtivaSP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DividaAtivaSPAsync(string token, string documento);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Relatorio", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RelatorioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFinal;
        
        public RelatorioRequest() {
        }
        
        public RelatorioRequest(string token, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFinal) {
            this.token = token;
            this.dataInicio = dataInicio;
            this.dataFinal = dataFinal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RelatorioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RelatorioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlNode RelatorioResult;
        
        public RelatorioResponse() {
        }
        
        public RelatorioResponse(System.Xml.XmlNode RelatorioResult) {
            this.RelatorioResult = RelatorioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsSoapChannel : Pulling.ValideInfo.WsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSoapClient : System.ServiceModel.ClientBase<Pulling.ValideInfo.WsSoap>, Pulling.ValideInfo.WsSoap {
        
        public WsSoapClient() {
        }
        
        public WsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GerarToken(int codigoEmpresa, string usuario, string senha) {
            return base.Channel.GerarToken(codigoEmpresa, usuario, senha);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GerarTokenAsync(int codigoEmpresa, string usuario, string senha) {
            return base.Channel.GerarTokenAsync(codigoEmpresa, usuario, senha);
        }
        
        public System.Xml.XmlNode Localiza(string token, string documento) {
            return base.Channel.Localiza(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> LocalizaAsync(string token, string documento) {
            return base.Channel.LocalizaAsync(token, documento);
        }
        
        public System.Xml.XmlNode CadastroSimplesPF(string token, string documento) {
            return base.Channel.CadastroSimplesPF(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroSimplesPFAsync(string token, string documento) {
            return base.Channel.CadastroSimplesPFAsync(token, documento);
        }
        
        public System.Xml.XmlNode CadastroSimplesPJ(string token, string documento) {
            return base.Channel.CadastroSimplesPJ(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroSimplesPJAsync(string token, string documento) {
            return base.Channel.CadastroSimplesPJAsync(token, documento);
        }
        
        public System.Xml.XmlNode CadastroSintetico(string token, string documento) {
            return base.Channel.CadastroSintetico(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroSinteticoAsync(string token, string documento) {
            return base.Channel.CadastroSinteticoAsync(token, documento);
        }
        
        public System.Xml.XmlNode CadastroCompletoPF(string token, string documento) {
            return base.Channel.CadastroCompletoPF(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroCompletoPFAsync(string token, string documento) {
            return base.Channel.CadastroCompletoPFAsync(token, documento);
        }
        
        public System.Xml.XmlNode CadastroCompletoPJ(string token, string documento) {
            return base.Channel.CadastroCompletoPJ(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CadastroCompletoPJAsync(string token, string documento) {
            return base.Channel.CadastroCompletoPJAsync(token, documento);
        }
        
        public System.Xml.XmlNode PessoasLigadas(string token, string documento) {
            return base.Channel.PessoasLigadas(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> PessoasLigadasAsync(string token, string documento) {
            return base.Channel.PessoasLigadasAsync(token, documento);
        }
        
        public System.Xml.XmlNode ReceitaFederalPFOnline(string token, string documento, string dataNascimento) {
            return base.Channel.ReceitaFederalPFOnline(token, documento, dataNascimento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPFOnlineAsync(string token, string documento, string dataNascimento) {
            return base.Channel.ReceitaFederalPFOnlineAsync(token, documento, dataNascimento);
        }
        
        public System.Xml.XmlNode ReceitaFederalPFBD(string token, string documento, string dataNascimento) {
            return base.Channel.ReceitaFederalPFBD(token, documento, dataNascimento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPFBDAsync(string token, string documento, string dataNascimento) {
            return base.Channel.ReceitaFederalPFBDAsync(token, documento, dataNascimento);
        }
        
        public System.Xml.XmlNode ReceitaFederalPJOnline(string token, string documento) {
            return base.Channel.ReceitaFederalPJOnline(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPJOnlineAsync(string token, string documento) {
            return base.Channel.ReceitaFederalPJOnlineAsync(token, documento);
        }
        
        public System.Xml.XmlNode ReceitaFederalPJBD(string token, string documento) {
            return base.Channel.ReceitaFederalPJBD(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalPJBDAsync(string token, string documento) {
            return base.Channel.ReceitaFederalPJBDAsync(token, documento);
        }
        
        public System.Xml.XmlNode ReceitaSintegraOnline(string token, string documento) {
            return base.Channel.ReceitaSintegraOnline(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaSintegraOnlineAsync(string token, string documento) {
            return base.Channel.ReceitaSintegraOnlineAsync(token, documento);
        }
        
        public System.Xml.XmlNode SintegraOnline(string token, string documento, string uf) {
            return base.Channel.SintegraOnline(token, documento, uf);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SintegraOnlineAsync(string token, string documento, string uf) {
            return base.Channel.SintegraOnlineAsync(token, documento, uf);
        }
        
        public System.Xml.XmlNode ValidacaoFiscal(string token, string documento) {
            return base.Channel.ValidacaoFiscal(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ValidacaoFiscalAsync(string token, string documento) {
            return base.Channel.ValidacaoFiscalAsync(token, documento);
        }
        
        public System.Xml.XmlNode Veiculo(string token, string placa) {
            return base.Channel.Veiculo(token, placa);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> VeiculoAsync(string token, string placa) {
            return base.Channel.VeiculoAsync(token, placa);
        }
        
        public System.Xml.XmlNode VeiculoSimples(string token, string placa) {
            return base.Channel.VeiculoSimples(token, placa);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> VeiculoSimplesAsync(string token, string placa) {
            return base.Channel.VeiculoSimplesAsync(token, placa);
        }
        
        public System.Xml.XmlNode ObitoSimples(string token, string documento) {
            return base.Channel.ObitoSimples(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObitoSimplesAsync(string token, string documento) {
            return base.Channel.ObitoSimplesAsync(token, documento);
        }
        
        public System.Xml.XmlNode GroupPJ(string token, string documento) {
            return base.Channel.GroupPJ(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GroupPJAsync(string token, string documento) {
            return base.Channel.GroupPJAsync(token, documento);
        }
        
        public System.Xml.XmlNode SimplesNacional(string token, string documento) {
            return base.Channel.SimplesNacional(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SimplesNacionalAsync(string token, string documento) {
            return base.Channel.SimplesNacionalAsync(token, documento);
        }
        
        public System.Xml.XmlNode Protesto(string token, string documento) {
            return base.Channel.Protesto(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ProtestoAsync(string token, string documento) {
            return base.Channel.ProtestoAsync(token, documento);
        }
        
        public System.Xml.XmlNode QSA(string token, string documento) {
            return base.Channel.QSA(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> QSAAsync(string token, string documento) {
            return base.Channel.QSAAsync(token, documento);
        }
        
        public System.Xml.XmlNode BuscaCEP(string token, string cep) {
            return base.Channel.BuscaCEP(token, cep);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> BuscaCEPAsync(string token, string cep) {
            return base.Channel.BuscaCEPAsync(token, cep);
        }
        
        public System.Xml.XmlNode BuscaCepPorLogradouro(string token, string estado, string cidade, string logradouro) {
            return base.Channel.BuscaCepPorLogradouro(token, estado, cidade, logradouro);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> BuscaCepPorLogradouroAsync(string token, string estado, string cidade, string logradouro) {
            return base.Channel.BuscaCepPorLogradouroAsync(token, estado, cidade, logradouro);
        }
        
        public System.Xml.XmlNode RestricaoS(string token, string documento) {
            return base.Channel.RestricaoS(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RestricaoSAsync(string token, string documento) {
            return base.Channel.RestricaoSAsync(token, documento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pulling.ValideInfo.RelatorioResponse Pulling.ValideInfo.WsSoap.Relatorio(Pulling.ValideInfo.RelatorioRequest request) {
            return base.Channel.Relatorio(request);
        }
        
        public System.Xml.XmlNode Relatorio(string token, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFinal) {
            Pulling.ValideInfo.RelatorioRequest inValue = new Pulling.ValideInfo.RelatorioRequest();
            inValue.token = token;
            inValue.dataInicio = dataInicio;
            inValue.dataFinal = dataFinal;
            Pulling.ValideInfo.RelatorioResponse retVal = ((Pulling.ValideInfo.WsSoap)(this)).Relatorio(inValue);
            return retVal.RelatorioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pulling.ValideInfo.RelatorioResponse> Pulling.ValideInfo.WsSoap.RelatorioAsync(Pulling.ValideInfo.RelatorioRequest request) {
            return base.Channel.RelatorioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pulling.ValideInfo.RelatorioResponse> RelatorioAsync(string token, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFinal) {
            Pulling.ValideInfo.RelatorioRequest inValue = new Pulling.ValideInfo.RelatorioRequest();
            inValue.token = token;
            inValue.dataInicio = dataInicio;
            inValue.dataFinal = dataFinal;
            return ((Pulling.ValideInfo.WsSoap)(this)).RelatorioAsync(inValue);
        }
        
        public System.Xml.XmlNode ANP(string token, string documento) {
            return base.Channel.ANP(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ANPAsync(string token, string documento) {
            return base.Channel.ANPAsync(token, documento);
        }
        
        public System.Xml.XmlNode ConsultaFGTSEmpregador(string token, string documento) {
            return base.Channel.ConsultaFGTSEmpregador(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultaFGTSEmpregadorAsync(string token, string documento) {
            return base.Channel.ConsultaFGTSEmpregadorAsync(token, documento);
        }
        
        public System.Xml.XmlNode Score(string token, string documento) {
            return base.Channel.Score(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ScoreAsync(string token, string documento) {
            return base.Channel.ScoreAsync(token, documento);
        }
        
        public System.Xml.XmlNode IRPF(string token, string documento, int exercicio) {
            return base.Channel.IRPF(token, documento, exercicio);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IRPFAsync(string token, string documento, int exercicio) {
            return base.Channel.IRPFAsync(token, documento, exercicio);
        }
        
        public System.Xml.XmlNode CARF(string token, string documento) {
            return base.Channel.CARF(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CARFAsync(string token, string documento) {
            return base.Channel.CARFAsync(token, documento);
        }
        
        public System.Xml.XmlNode ConsultaTSE(string token, string documento) {
            return base.Channel.ConsultaTSE(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultaTSEAsync(string token, string documento) {
            return base.Channel.ConsultaTSEAsync(token, documento);
        }
        
        public System.Xml.XmlNode CCF(string token, string documento) {
            return base.Channel.CCF(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CCFAsync(string token, string documento) {
            return base.Channel.CCFAsync(token, documento);
        }
        
        public System.Xml.XmlNode ReceitaFederalComCaptcha(string token, string cpf, string dataNascimento, string captcha) {
            return base.Channel.ReceitaFederalComCaptcha(token, cpf, dataNascimento, captcha);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReceitaFederalComCaptchaAsync(string token, string cpf, string dataNascimento, string captcha) {
            return base.Channel.ReceitaFederalComCaptchaAsync(token, cpf, dataNascimento, captcha);
        }
        
        public System.Xml.XmlNode MandadoPrisao(string token, string nome, string dataNascimento, string nomeMae) {
            return base.Channel.MandadoPrisao(token, nome, dataNascimento, nomeMae);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> MandadoPrisaoAsync(string token, string nome, string dataNascimento, string nomeMae) {
            return base.Channel.MandadoPrisaoAsync(token, nome, dataNascimento, nomeMae);
        }
        
        public System.Xml.XmlNode PEP(string token, string documento) {
            return base.Channel.PEP(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> PEPAsync(string token, string documento) {
            return base.Channel.PEPAsync(token, documento);
        }
        
        public System.Xml.XmlNode AcoesJudiciais(string token, string documento) {
            return base.Channel.AcoesJudiciais(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AcoesJudiciaisAsync(string token, string documento) {
            return base.Channel.AcoesJudiciaisAsync(token, documento);
        }
        
        public System.Xml.XmlNode SugereGEO(string token, string documento, string cep) {
            return base.Channel.SugereGEO(token, documento, cep);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SugereGEOAsync(string token, string documento, string cep) {
            return base.Channel.SugereGEOAsync(token, documento, cep);
        }
        
        public System.Xml.XmlNode JusBrasilPF(string token, string documento) {
            return base.Channel.JusBrasilPF(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> JusBrasilPFAsync(string token, string documento) {
            return base.Channel.JusBrasilPFAsync(token, documento);
        }
        
        public System.Xml.XmlNode BACEN(string token, string cnpj, string unidade, string dependencia, string operador, string mes, string ano, string senha) {
            return base.Channel.BACEN(token, cnpj, unidade, dependencia, operador, mes, ano, senha);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> BACENAsync(string token, string cnpj, string unidade, string dependencia, string operador, string mes, string ano, string senha) {
            return base.Channel.BACENAsync(token, cnpj, unidade, dependencia, operador, mes, ano, senha);
        }
        
        public System.Xml.XmlNode CEPIM(string token, string documento) {
            return base.Channel.CEPIM(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CEPIMAsync(string token, string documento) {
            return base.Channel.CEPIMAsync(token, documento);
        }
        
        public System.Xml.XmlNode CEIS(string token, string documento) {
            return base.Channel.CEIS(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CEISAsync(string token, string documento) {
            return base.Channel.CEISAsync(token, documento);
        }
        
        public System.Xml.XmlNode CNEP(string token, string documento) {
            return base.Channel.CNEP(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CNEPAsync(string token, string documento) {
            return base.Channel.CNEPAsync(token, documento);
        }
        
        public System.Xml.XmlNode PETI(string token, string documento) {
            return base.Channel.PETI(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> PETIAsync(string token, string documento) {
            return base.Channel.PETIAsync(token, documento);
        }
        
        public System.Xml.XmlNode AcordoLeniencia(string token, string documento) {
            return base.Channel.AcordoLeniencia(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AcordoLenienciaAsync(string token, string documento) {
            return base.Channel.AcordoLenienciaAsync(token, documento);
        }
        
        public System.Xml.XmlNode CEAF(string token, string documento) {
            return base.Channel.CEAF(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CEAFAsync(string token, string documento) {
            return base.Channel.CEAFAsync(token, documento);
        }
        
        public System.Xml.XmlNode DividaAtivaSP(string token, string documento) {
            return base.Channel.DividaAtivaSP(token, documento);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DividaAtivaSPAsync(string token, string documento) {
            return base.Channel.DividaAtivaSPAsync(token, documento);
        }
    }
}
